// Mappa di normalizzazione dei nomi dei paesi
export const NORMALIZED_COUNTRIES: Record<string, string> = {
  // Europa
  'italia': 'Italy',
  'italy': 'Italy',
  'it': 'Italy',
  'france': 'France',
  'francia': 'France',
  'fr': 'France',
  'germany': 'Germany',
  'germania': 'Germany',
  'deutschland': 'Germany',
  'de': 'Germany',
  'spain': 'Spain',
  'españa': 'Spain',
  'spagna': 'Spain',
  'es': 'Spain',
  'portugal': 'Portugal',
  'portogallo': 'Portugal',
  'pt': 'Portugal',
  'united kingdom': 'United Kingdom',
  'regno unito': 'United Kingdom',
  'uk': 'United Kingdom',
  'gb': 'United Kingdom',
  'netherlands': 'Netherlands',
  'paesi bassi': 'Netherlands',
  'olanda': 'Netherlands',
  'nl': 'Netherlands',
  'belgium': 'Belgium',
  'belgio': 'Belgium',
  'be': 'Belgium',
  'switzerland': 'Switzerland',
  'svizzera': 'Switzerland',
  'schweiz': 'Switzerland',
  'ch': 'Switzerland',
  'austria': 'Austria',
  'at': 'Austria',
  'greece': 'Greece',
  'grecia': 'Greece',
  'gr': 'Greece',
  'sweden': 'Sweden',
  'svezia': 'Sweden',
  'se': 'Sweden',
  'norway': 'Norway',
  'norvegia': 'Norway',
  'no': 'Norway',
  'denmark': 'Denmark',
  'danimarca': 'Denmark',
  'dk': 'Denmark',
  'finland': 'Finland',
  'finlandia': 'Finland',
  'fi': 'Finland',
  'ireland': 'Ireland',
  'irlanda': 'Ireland',
  'ie': 'Ireland',

  // America
  'united states': 'United States',
  'stati uniti': 'United States',
  'usa': 'United States',
  'us': 'United States',
  'canada': 'Canada',
  'ca': 'Canada',
  'mexico': 'Mexico',
  'messico': 'Mexico',
  'mx': 'Mexico',
  'brazil': 'Brazil',
  'brasil': 'Brazil',
  'brasile': 'Brazil',
  'br': 'Brazil',
  'argentina': 'Argentina',
  'ar': 'Argentina',

  // Asia
  'japan': 'Japan',
  'giappone': 'Japan',
  'jp': 'Japan',
  'china': 'China',
  'cina': 'China',
  'cn': 'China',
  'india': 'India',
  'in': 'India',
  'south korea': 'South Korea',
  'corea del sud': 'South Korea',
  'kr': 'South Korea',
  'singapore': 'Singapore',
  'sg': 'Singapore',

  // Oceania
  'australia': 'Australia',
  'au': 'Australia',
  'new zealand': 'New Zealand',
  'nuova zelanda': 'New Zealand',
  'nz': 'New Zealand',

  // Africa
  'south africa': 'South Africa',
  'sudafrica': 'South Africa',
  'za': 'South Africa',
  'egypt': 'Egypt',
  'egitto': 'Egypt',
  'eg': 'Egypt',
  'morocco': 'Morocco',
  'marocco': 'Morocco',
  'ma': 'Morocco'
};

export const normalizeCountryName = (country: string | undefined): string => {
  if (!country) return 'Unknown';
  const normalized = NORMALIZED_COUNTRIES[country.toLowerCase().trim()];
  return normalized || country;
}; 